Animals game
migrave/migrave_behaviour_manager pull request #4
Opened 2022-12-19 15:20 UTC by natalialqp

Modify game according to the new changes of the game structure.
Correct images and highlighted images are lists.

2022-12-19 15:56 UTC, alex-mitrevski requested changes

2022-12-19 15:56 UTC, alex-mitrevski commented on ros/src/migrave_game_library/animals.py
> +            # self.activity_parameters.images = [f"{x}-cartoon" for x in possible_animals]
Can this line be removed?

2022-12-19 15:56 UTC, alex-mitrevski commented on ros/src/migrave_game_library/animals.py
> +            # self.activity_parameters.images = [f"{x}-black-white" for x in possible_animals]
Same as above.

2022-12-19 15:56 UTC, alex-mitrevski commented on ros/src/migrave_game_library/animals.py
> +            # self.activity_parameters.images = [f"{x}-draw" for x in possible_animals]
Same as above.

2022-12-21 09:22 UTC, natalialqp commented
Done with the changes

2022-12-22 08:38 UTC, merged